### ISSUE TITLE
Rule EC66 does not apply to the Python language 

### ISSUE THREAD

**Issue by dedece35** [green-code-initiative/ecoCode-python#4]
please check the analysis done in closed issue in old repository : https://github.com/green-code-initiative/ecoCode/issues/198
existing rule in SonarQube : quite the same subject => "python:S3457"

TO DISCUSS INSIDE CORE_TEAM : opinion ? I'm ok with analysis (Python expert)

**Comment by dedece35** [comment]
after discussion with core-team ... @jhertout will see it and we will come back here

**Comment by jhertout** [comment]
Hello, I perform some investigation and I confirm the analysis done in https://github.com/green-code-initiative/ecoCode/issues/198. 
I cannot see differences in the bytecode too and when going through the python documentation they explicitly say that they can be used indifferently.

I think we can remove this rule for Python. It is not an "instinctive rule" for Python and the documentation and first impression are likely to show that there are no differences. 
For me, if this rule is true, measures MUST be done because without them, everything seems to indicate there is no differences.

**Comment by dedece35** [comment]
Hi @jhertout,
thank you for analysis.
ok, I will remove this rule for python and I will create a new MD file to reference this kind of work which must be done.
(plop @glalloue )

**Comment by dedece35** [comment]
deprecation of EC66 rule done in PRs :
- `ecocode`repo : https://github.com/green-code-initiative/ecoCode/pull/261
- `ecocode-python` repo : https://github.com/green-code-initiative/ecoCode-python/pull/9
